import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Loan } from './loan.entity';

export enum LoanTransactionType {
  // System-generated by LoansService.syncAccruals — one per calendar
  // month, only for isInterestOnly loans while ACTIVE.
  INTEREST_ACCRUAL = 'INTEREST_ACCRUAL',
  // Admin-recorded via POST /loans/:id/repay.
  REPAYMENT = 'REPAYMENT',
}

// A single entry in a loan's ledger. principalAmount/interestAmount are
// always positive magnitudes — type decides the direction: an accrual
// adds to interestOutstanding, a repayment subtracts its principal/
// interest amounts from principalOutstanding/interestOutstanding
// respectively (principalAmount is always 0 on an accrual row). Mirrors
// investments/withdrawal.entity.ts's amount+type convention, just with
// two amount columns instead of one since a single repayment can cover
// both principal and interest at once.
@Entity('loan_transactions')
export class LoanTransaction {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  loanId: number;

  @ManyToOne(() => Loan)
  @JoinColumn({ name: 'loanId' })
  loan: Loan;

  @Column({ type: 'enum', enum: LoanTransactionType })
  type: LoanTransactionType;

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  principalAmount: number;

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  interestAmount: number;

  @Column({ type: 'date' })
  date: string;

  @Column({ type: 'text', nullable: true })
  notes: string | null;

  @CreateDateColumn()
  createdAt: Date;
}
